name = "dewey"
version = "0.1.0"

description = "A Meilisearch client for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "tylermeekel", repo = "dewey" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
